### ISSUE TITLE
Plugin closed in WordPress plugins directory?

### ISSUE THREAD

**Issue by strarsis** [Weather-Station-Software/live-weather-station#42]
The Live Weather Station plugin is now closed in the WordPress plugins directory:
https://wordpress.org/plugins/live-weather-station/

Is this plugin published under a different name, or only over GitHub now?

**Comment by dorianwoolger** [comment]
Have same issue. Also tried installing from source but it crashes on activation.

> Fatal error: Uncaught Error: Call to undefined method WeatherStation\System\Environment\Manager::is_updatable() in /home/nairodco/public_html/wp-content/plugins/live-weather-station/includes/traits/SystemOptionsHandling.php:1163 Stack trace: #0 /home/nairodco/public_html/wp-content/plugins/live-weather-station/includes/classes/SystemPluginCore.php(294): WeatherStation\System\Plugin\Core::verify_options() #1 /home/nairodco/public_html/wp-content/plugins/live-weather-station/includes/classes/SystemPluginCore.php(309): WeatherStation\System\Plugin\Core->check_and_perform_update() #2 /home/nairodco/public_html/wp-content/plugins/live-weather-station/init.php(91): WeatherStation\System\Plugin\Core->run() #3 /home/nairodco/public_html/wp-content/plugins/live-weather-station/live-weather-station.php(66): run_Live_Weather_Station() #4 /home/nairodco/public_html/wp-admin/includes/plugin.php(2318): include_once('/home/nairodco/...') #5 /home/nairodco/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape('live-weather-st...') in /home/nairodco/public_html/wp-content/plugins/live-weather-station/includes/traits/SystemOptionsHandling.php on line 1163

**Comment by HenrikBoChristoffersen** [comment]
I have the same issue, but it looks like it's temporary pending a full review of code. However; it would be highly appreciated if we could get an update on what is happening.

**Comment by robin-scott** [comment]
I built a site with this plugin a long time ago; was considering it for another project & came across the more recent announcements.

WordPress plugins team have taken this plugin out of the official repo pending review - likely because the ownership has changed. A lot of plugins will use a change of ownership to slide through weird stuff, which is why this triggers an additional manual review. 

For users: wait is the only option!

For maintainer: let me know if you'd like to get plugins team to take a look, as I'm in the community with some of those good people. Hit the official WordPress slack to discuss there.

For the time being, I'm going to pull down from the source here to play with this & will try to contribute back if I do install for our weather stations.

Good luck to all!

**Comment by GWCTas** [comment]
I apologise in advance if I am wrong, but to me the plugin has not lived up to the promise of the new ownership. I and others have posted issues on here last year and limited or no response from the developer. Sadly, I think this once great plugin is dead. To Pierre, what a shame after all the work you did.

**Comment by labbs1** [comment]
Is this no more?
Can we please get an update cause it is no longer possible to enable this plugin in WP since they considder it unsafe.
